language: csharp
mono: none
dotnet: 2.0.0

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: xenial
    - os: osx # OSX 10.12
      osx_image: xcode9.2
    - os: windows # Windows Server version 1803

script:
  - dotnet --info
  - dotnet build
